<x-layouts.app :title="$title" :dashboard="true">
    @php
        $user = auth()->user();
        $roleLabel = ['CLIENT' => __('Client'), 'PROVIDER' => __('Provider'), 'ADMIN' => __('Administrator')][$user->role];
    @endphp
    <div class="min-h-screen bg-slate-50">
        <div class="flex min-h-screen w-full">
            <aside id="dashboard-sidebar" class="fixed inset-y-0 left-0 z-50 hidden w-72 flex-col bg-slate-950 px-4 py-5 text-slate-300 shadow-2xl lg:sticky lg:top-0 lg:flex lg:h-screen lg:shrink-0">
                <div class="flex items-center justify-between px-2"><x-logo class="text-white [&>span:last-child]:text-white" /><button type="button" data-dashboard-nav-toggle class="grid size-10 place-items-center rounded-lg text-slate-300 hover:bg-white/10 lg:hidden"><span class="sr-only">Close navigation</span><svg class="size-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" d="m6 6 12 12M18 6 6 18" /></svg></button></div>
                <div class="mt-8 rounded-2xl border border-white/10 bg-white/5 p-4"><p class="text-xs font-semibold uppercase tracking-wider text-sky-300">{{ __(':role workspace', ['role' => $roleLabel]) }}</p><p class="mt-2 truncate font-semibold text-white">{{ $user->name }}</p><p class="mt-1 text-xs leading-5 text-slate-400">{{ $user->role === 'CLIENT' ? __('Personal electricity updates') : ($user->role === 'PROVIDER' ? __('Network publishing and visibility') : __('Platform supervision and control')) }}</p></div>
                <nav class="mt-8 space-y-1" aria-label="{{ __('Dashboard navigation') }}"><p class="px-3 pb-2 text-xs font-semibold uppercase tracking-wider text-slate-500">{{ __('Workspace') }}</p><a href="{{ route('dashboard') }}" @class(['flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium transition', 'bg-sky-600 text-white shadow-sm' => request()->routeIs('dashboard'), 'text-slate-300 hover:bg-white/10 hover:text-white' => !request()->routeIs('dashboard')])><svg class="size-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.8"><path stroke-linecap="round" stroke-linejoin="round" d="M3.75 3v18h16.5V3H3.75Zm4.5 4.5h.008v.008H8.25V7.5Zm0 4.5h.008v.008H8.25V12Zm0 4.5h.008v.008H8.25v-.008ZM12 7.5h3.75M12 12h3.75M12 16.5h3.75" /></svg>{{ __('Overview') }}</a>
                    <a href="{{ route('dashboard') }}#network-map" class="flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium text-slate-300 transition hover:bg-white/10 hover:text-white"><svg class="size-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.8"><path stroke-linecap="round" stroke-linejoin="round" d="m3.75 6 5.25-3 6 3 5.25-3v15L15 21l-6-3-5.25 3V6Z" /><path stroke-linecap="round" d="M9 3v15m6-12v15" /></svg>{{ __('Network map') }}</a>
                    @if($user->hasRole('CLIENT'))<a href="{{ route('locations.index') }}" @class(['flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium transition', 'bg-sky-600 text-white shadow-sm' => request()->routeIs('locations.*'), 'text-slate-300 hover:bg-white/10 hover:text-white' => !request()->routeIs('locations.*')])><svg class="size-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.8"><path stroke-linecap="round" stroke-linejoin="round" d="M12 21s6-5.73 6-12A6 6 0 0 0 6 9c0 6.27 6 12 6 12Z" /><path stroke-linecap="round" d="M12 11.25a2.25 2.25 0 1 0 0-4.5 2.25 2.25 0 0 0 0 4.5Z" /></svg>{{ __('My locations') }}</a><a href="{{ route('reports.create') }}" @class(['flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium transition', 'bg-sky-600 text-white shadow-sm' => request()->routeIs('reports.*'), 'text-slate-300 hover:bg-white/10 hover:text-white' => !request()->routeIs('reports.*')])><svg class="size-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.8"><path stroke-linecap="round" stroke-linejoin="round" d="M12 9v3.75m9-.75a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" /></svg>{{ __('Report outage') }}</a><a href="{{ route('notifications.index') }}" @class(['flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium transition', 'bg-sky-600 text-white shadow-sm' => request()->routeIs('notifications.*'), 'text-slate-300 hover:bg-white/10 hover:text-white' => !request()->routeIs('notifications.*')])><svg class="size-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.8"><path stroke-linecap="round" stroke-linejoin="round" d="M14.857 17.082a23.848 23.848 0 0 0 5.454-1.31A8.967 8.967 0 0 1 18 9.75V9A6 6 0 0 0 6 9v.75a8.967 8.967 0 0 1-2.312 6.022c1.733.64 3.56 1.085 5.455 1.31" /></svg>{{ __('Notifications') }}</a>@endif
                    @if($user->hasRole('CLIENT'))<a href="{{ route('bills.index') }}" @class(['flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium transition', 'bg-sky-600 text-white shadow-sm' => request()->routeIs('bills.*'), 'text-slate-300 hover:bg-white/10 hover:text-white' => !request()->routeIs('bills.*')])><svg class="size-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.8"><path stroke-linecap="round" stroke-linejoin="round" d="M12 3h7.5A1.5 1.5 0 0 1 21 4.5v15a1.5 1.5 0 0 1-1.5 1.5h-15A1.5 1.5 0 0 1 3 19.5v-15A1.5 1.5 0 0 1 4.5 3H7" /><path stroke-linecap="round" d="M8.25 3.75h7.5V7.5h-7.5zM7.5 12h9m-9 3h6" /></svg>{{ __('My bills') }}</a>@endif
                    @if($user->hasRole('PROVIDER', 'ADMIN'))<a href="{{ route('outages.manage') }}" @class(['flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium transition', 'bg-sky-600 text-white shadow-sm' => request()->routeIs('outages.manage*'), 'text-slate-300 hover:bg-white/10 hover:text-white' => !request()->routeIs('outages.manage*')])><svg class="size-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.8"><path stroke-linecap="round" stroke-linejoin="round" d="M12 3v18m9-9H3" /></svg>{{ __('Manage outages') }}</a>@endif
                    @if($user->hasRole('ADMIN'))<a href="{{ route('admin.map-settings.edit') }}" @class(['flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium transition', 'bg-sky-600 text-white shadow-sm' => request()->routeIs('admin.map-settings.*'), 'text-slate-300 hover:bg-white/10 hover:text-white' => !request()->routeIs('admin.map-settings.*')])><svg class="size-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.8"><path stroke-linecap="round" stroke-linejoin="round" d="M12 3v18m9-9H3" /></svg>Map provider</a>@endif
                    <a href="{{ route('community.index') }}" @class(['flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium transition', 'bg-sky-600 text-white shadow-sm' => request()->routeIs('community.*'), 'text-slate-300 hover:bg-white/10 hover:text-white' => !request()->routeIs('community.*')])><svg class="size-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.8"><path stroke-linecap="round" stroke-linejoin="round" d="M8.25 10.5h7.5M8.25 14.25h4.5M18.75 19.5l-3.15-2.1a9 9 0 1 1 3.15-6.9v9Z" /></svg>{{ __('Community') }}</a>
                    <a href="{{ route('outages.index') }}" class="flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium text-slate-300 transition hover:bg-white/10 hover:text-white"><svg class="size-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.8"><path stroke-linecap="round" stroke-linejoin="round" d="M3.75 15.75 9 10.5l3.75 3.75L20.25 6" /><path stroke-linecap="round" d="M17.25 6h3v3" /></svg>{{ __('Outage board') }}</a>
                </nav>
                <div class="mt-auto border-t border-white/10 pt-5"><form method="POST" action="{{ route('logout') }}">@csrf <button class="flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium text-slate-300 transition hover:bg-white/10 hover:text-white"><svg class="size-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.8"><path stroke-linecap="round" stroke-linejoin="round" d="M15.75 9V5.25A2.25 2.25 0 0 0 13.5 3h-6A2.25 2.25 0 0 0 5.25 5.25v13.5A2.25 2.25 0 0 0 7.5 21h6a2.25 2.25 0 0 0 2.25-2.25V15M18 12H9m9 0-3-3m3 3-3 3" /></svg>{{ __('Sign out') }}</button></form></div>
            </aside>
            <div class="min-w-0 flex-1"><header class="sticky top-0 z-30 flex h-16 items-center justify-between border-b border-slate-200 bg-white/95 px-4 backdrop-blur sm:px-6 lg:px-8"><button type="button" data-dashboard-nav-toggle aria-expanded="false" aria-controls="dashboard-sidebar" class="grid size-10 place-items-center rounded-lg text-slate-700 hover:bg-slate-100 lg:hidden"><span class="sr-only">Open navigation</span><svg class="size-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" d="M4 6h16M4 12h16M4 18h16" /></svg></button><div class="hidden text-sm text-slate-500 sm:block">{{ now()->format('l, d F Y') }}</div><div class="flex items-center gap-3"><form method="POST" action="{{ route('locale.update') }}">@csrf <select aria-label="Language" name="locale" onchange="this.form.submit()" class="rounded-lg border-0 bg-transparent py-2 pl-2 pr-7 text-sm font-medium text-slate-600 outline-none focus:ring-2 focus:ring-sky-600"><option value="en" @selected(app()->getLocale() === 'en')>EN</option><option value="fr" @selected(app()->getLocale() === 'fr')>FR</option></select></form><div class="grid size-9 place-items-center rounded-full bg-sky-100 text-sm font-bold text-sky-800">{{ mb_strtoupper(mb_substr($user->name, 0, 1)) }}</div></div></header><main id="main-content" class="min-h-[calc(100dvh-4rem)] p-4 sm:p-6 lg:p-8">{{ $slot }}</main></div>
        </div>
    </div>
</x-layouts.app>
